version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"