name: Deploy without Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Frontend
      working-directory: client
      run: |
        npm install
        npm run build

    - name: Build Backend
      working-directory: server
      run: |
        mvn clean install -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

    - name: Publish Localhost without Docker
      working-directory: server
      run: |
        java -jar back-end-0.0.1-SNAPSHOT.jar
